services:
  dataset-service:
    build:
      context: ./services/dataset-service
      dockerfile: Dockerfile
    container_name: high-scale-cyber-ml-dataset
    ports:
      - "2000:8000"
    environment:
      DATA_DIR: "${DATA_DIR:-/shared/data/raw}"
    volumes:
      - ./shared/data:/shared/data
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.9.1
    container_name: high-scale-cyber-ml-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: CONTROLLER://:9093,PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

  streaming-service:
    build:
      context: ./services/streaming-service
      dockerfile: Dockerfile
    container_name: high-scale-cyber-ml-streaming
    ports:
      - "2050:8000"
    environment:
      DATA_DIR: /shared/data/raw
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: unsw-events
      KAFKA_PARTITIONS: 4
    volumes:
      - ./shared/data:/shared/data:ro
    depends_on:
      - kafka
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: high-scale-cyber-ml-redis
    command: ["redis-server", "--appendonly", "no"]
    restart: unless-stopped

  feature-service:
    build:
      context: ./services/feature-service
      dockerfile: Dockerfile
    container_name: high-scale-cyber-ml-feature
    ports:
      - "2100:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: unsw-events
      KAFKA_GROUP_ID: feature-service
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FEATURE_TTL_SECONDS: 3600
      WINDOW_SECONDS: 60
    depends_on:
      - kafka
      - redis
    restart: unless-stopped

volumes:
  kafka-data: